// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBcdG4HebzrnH3N2r_035AqB772rMSFHM',
    appId: '1:191185633483:android:be25313ef87d7288419b4e',
    messagingSenderId: '191185633483',
    projectId: 'turf-arena',
    storageBucket: 'turf-arena.firebasestorage.app',
  );

  // Old Creds by Flash Chat. Have to Modify these
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBcdG4HebzrnH3N2r_035AqB772rMSFHM',
    appId: '27091:191185633483:android:be25313ef87d7288419b4e',
    messagingSenderId: '191185633483',
    projectId: 'turf-arena',
    storageBucket: 'turf-arena.firebasestorage.app',
    // authDomain: 'flash-chat-1a4b5.firebaseapp.com',
    // measurementId: 'G-CDBJF66M33',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBcdG4HebzrnH3N2r_035AqB772rMSFHM',
    appId: '1:191185633483:android:be25313ef87d7288419b4e',
    messagingSenderId: '191185633483',
    projectId: 'turf-arena',
    storageBucket: 'turf-arena.firebasestorage.app',
    iosBundleId: 'com.example.turf_arena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBcdG4HebzrnH3N2r_035AqB772rMSFHM',
    appId: '1:191185633483:android:be25313ef87d7288419b4e',
    messagingSenderId: '191185633483',
    projectId: 'turf-arena',
    storageBucket: 'turf-arena.firebasestorage.app',
    iosBundleId: 'com.example.turf_arena.RunnerTests',
  );
}
